storage.backend=cql
storage.hostname=localhost
storage.cql.keyspace=janusgraph
storage.cql.replication-factor=1
storage.cql.read-consistency-level=ONE
storage.cql.write-consistency-level=ONE
storage.lock.wait-time=100
storage.lock.clean-expired=true
storage.transactions=false
storage.batch-loading=true
ids.flush=false
query.force-index=false
graph.set-vertex-id=true
graph.set-edge-id=true
graph.allow-custom-vid-types=true
graph.allow-custom-eid-types=true
