storage.backend=cql
storage.hostname=localhost
storage.cql.keyspace=janusgraph
storage.cql.replication-factor=1
storage.cql.read-consistency-level=ONE
storage.cql.write-consistency-level=ONE
storage.cql.local-datacenter=datacenter1
storage.lock.wait-time=100
storage.lock.clean-expired=true
storage.transactions=false
storage.batch-loading=true
storage.buffer-size=20480
storage.parallel-backend-ops=true
ids.flush=false
ids.block-size=200000
ids.renew-timeout=300000
query.force-index=false
cache.db-cache=false
cache.tx-cache-size=100000
cache.tx-dirty-size=100000
graph.set-vertex-id=true
graph.set-edge-id=true
graph.allow-custom-vid-types=true
graph.allow-custom-eid-types=true

index.search.backend=elasticsearch
index.search.hostname=localhost:9200
