storage.backend=cql
storage.hostname=localhost
storage.cql.keyspace=janusgraph
storage.cql.replication-factor=1
storage.cql.read-consistency-level=ONE
storage.cql.write-consistency-level=ONE
storage.cql.only-use-local-consistency-for-system-operations=true
storage.lock.wait-time=10000
storage.lock.retries=3
storage.lock.clean-expired=true
storage.batch-loading=false
ids.flush=true
query.force-index=false
query.smart-limit=false
schema.default=none
cache.db-cache=false
graph.set-vertex-id=true
graph.set-edge-id=true
graph.allow-custom-vid-types=true
graph.allow-custom-eid-types=true
